In [24]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy.optimize import fmin_cobyla

# P4

## (a)

In [25]:

# Parameters
pi = np.array([0.8, 0.2])  # Probabilities of the states
e_A = np.array([300, 550])  # Endowment for Aaron
e_B = np.array([900, 500])  # Endowment for Bryan

theta_A = theta_B = 2.0  # Risk aversion coefficients
e_total = e_A + e_B  # Total endowment

In [26]:
# Agent optimization problem
def compute_optimal_consumption(e, theta, p, pi):
    # Compute the ratio of x_1 to x_0 from FOC
    ratio = (pi[1] * p[0] / (pi[0] * p[1]))**(1 / theta)
    
    # Budget constraint: p[0]*x0 + p[1]*x1 = p[0]*e[0] + p[1]*e[1]
    # Substitute x1 = ratio * x0 into the budget
    x0 = (p[0] * e[0] + p[1] * e[1]) / (p[0] + p[1] * ratio)
    x1 = ratio * x0
    
    return np.array([x0, x1])

In [27]:
def check_market_clearing(consumption_A, consumption_B, endowment_total):

    # Compute total consumption in each state
    total_consumption = consumption_A + consumption_B 

    # Compute residuals
    residuals = total_consumption - endowment_total

    return residuals

In [28]:

def find_market_clearing_price(e_A, e_B, theta_A, theta_B, pi, tol=1e-6, max_iter=1000):
    p1 = 0.5  # Initial guess of p[0]
    p_bounds = np.array([0.0, 1.0])  # Bounds for p[0]
    err = 1  # Initialize error
    n_iter = max_iter  # Initialize iteration counter
    iteration = 1
    while (err > tol) and (n_iter > iteration):
        # print("Iteration :", iteration)
        iteration += 1
        # Define the price vector
        p = np.array([p1, 1 - p1])
        # Compute optimal consumptions for each trader
        x_A = compute_optimal_consumption(e_A, theta_A, p, pi)
        x_B = compute_optimal_consumption(e_B, theta_B, p, pi)
        # Check market clearing
        residuals = check_market_clearing(x_A, x_B, e_total)
        err = np.linalg.norm(residuals)

        # Check convergence
        if err > tol:
            if residuals[0] > 0:
                # print(f"Market clearing error is positive {residuals[0]}, increase p1")
                p1_new = (p_bounds[1] + p1) / 2
                p_bounds[0] = p1
                p1 = p1_new
                # print("New p1:", p1)
                # print("New bounds:", p_bounds)
            else:
                # print(f"Market clearing error is negative {residuals[0]}, decrease p1")
                p1_new = (p1 + p_bounds[0]) / 2
                p_bounds[1] = p1
                p1 = p1_new
                # print("New p1:", p1)
                # print("New bounds:", p_bounds)

    return np.array([p1, 1 - p1])

# Example usage
p_market_clearing = find_market_clearing_price(e_A, e_B, theta_A, theta_B, pi)
central_factor=1/p_market_clearing[0]
central_price=p_market_clearing*central_factor
print("Market clearing prices p:", np.round(central_price, 2))


Market clearing prices p: [1.   0.33]


In [29]:

# Compute the stochastic discount factor (SDF) for each state
m = central_price / pi  # SDF = Arrow prices / state probabilities
avg_m = np.dot(m , pi)  # Average SDF
print("Stochastic discount factor (SDF) in each state:", np.round(m, 2))
q= m * pi / avg_m
print("Q:", np.round(q, 2))


Stochastic discount factor (SDF) in each state: [1.25 1.63]
Q: [0.75 0.25]


## (b)

In [30]:
def compute_asset_price(A, m, pi):

    return np.sum(A * m * pi)

# Example usage
A_1 = np.array([1, 1])  
A_2 = np.array([5, 0])  
P_1 = compute_asset_price(A_1, m, pi)
P_2 = compute_asset_price(A_2, m, pi)

print("Price of the asset with payoffs A_1 is P_1 =", np.round(P_1, 2))
print("Price of the asset with payoffs A_2 is P_2 =", np.round(P_2, 2))

Price of the asset with payoffs A_1 is P_1 = 1.33
Price of the asset with payoffs A_2 is P_2 = 5.0


## (c)

In [31]:
p = central_price  # Example Arrow prices (normalized to sum to 1)

# Compute optimal consumptions for each trader
x_A = compute_optimal_consumption(e_A, theta_A, p, pi)
x_B = compute_optimal_consumption(e_B, theta_B, p, pi)

print("Aaron's optimal consumption:", x_A)
print("Baron's optimal consumption:", x_B)

check_market_clearing(x_A, x_B, e_total)

Aaron's optimal consumption: [373.01587314 326.38888879]
Baron's optimal consumption: [826.98412703 723.6111107 ]


array([ 1.64723815e-07, -5.04466470e-07])

## (d)

In [ ]:
theta_B = 2.5
p_market_clearing = find_market_clearing_price(e_A, e_B, theta_A, theta_B, pi)
central_factor=1/p_market_clearing[0]
central_price=p_market_clearing*central_factor
print("Market clearing prices p:", np.round(central_price, 2))


# Compute the stochastic discount factor (SDF) for each state
m = central_price / pi  # SDF = Arrow prices / state probabilities
avg_m = np.dot(m , pi)  # Average SDF
print("Stochastic discount factor (SDF) in each state:", np.round(m, 2))
q= m * pi / avg_m
print("Q:", np.round(q, 2))

def compute_asset_price(A, m, pi):

    return np.sum(A * m * pi)

# Example usage
A_1 = np.array([1, 1])  
A_2 = np.array([5, 0])  
P_1 = compute_asset_price(A_1, m, pi)
P_2 = compute_asset_price(A_2, m, pi)

print("Price of the asset with payoffs A_1 is P_1 =", np.round(P_1, 2))
print("Price of the asset with payoffs A_2 is P_2 =", np.round(P_2, 2))

p = central_price

# Compute optimal consumptions for each trader
x_A = compute_optimal_consumption(e_A, theta_A, p, pi)
x_B = compute_optimal_consumption(e_B, theta_B, p, pi)

print("Aaron's optimal consumption:", x_A)
print("Baron's optimal consumption:", x_B)

check_market_clearing(x_A, x_B, e_total)

Market clearing prices p: [1.   0.34]
Stochastic discount factor (SDF) in each state: [1.25 1.7 ]
Q: [0.75 0.25]
Price of the asset with payoffs A_1 is P_1 = 1.34
Price of the asset with payoffs A_2 is P_2 = 5.0
Aaron's optimal consumption: [377.29776185 323.16564651]
Baron's optimal consumption: [822.70223816 726.83435346]


array([ 1.24121016e-08, -3.64236712e-08])

In [ ]:
theta_B = 3
p_market_clearing = find_market_clearing_price(e_A, e_B, theta_A, theta_B, pi)
central_factor=1/p_market_clearing[0]
central_price=p_market_clearing*central_factor
print("Market clearing prices p:", np.round(central_price, 2))


# Compute the stochastic discount factor (SDF) for each state
m = central_price / pi  # SDF = Arrow prices / state probabilities
avg_m = np.dot(m , pi)  # Average SDF
print("Stochastic discount factor (SDF) in each state:", np.round(m, 2))
q= m * pi / avg_m
print("Q:", np.round(q, 2))

def compute_asset_price(A, m, pi):

    return np.sum(A * m * pi)

# Example usage
A_1 = np.array([1, 1])  
A_2 = np.array([5, 0])  
P_1 = compute_asset_price(A_1, m, pi)
P_2 = compute_asset_price(A_2, m, pi)

print("Price of the asset with payoffs A_1 is P_1 =", np.round(P_1, 2))
print("Price of the asset with payoffs A_2 is P_2 =", np.round(P_2, 2))
p = central_price

# Compute optimal consumptions for each trader
x_A = compute_optimal_consumption(e_A, theta_A, p, pi)
x_B = compute_optimal_consumption(e_B, theta_B, p, pi)

print("Aaron's optimal consumption:", x_A)
print("Baron's optimal consumption:", x_B)

check_market_clearing(x_A, x_B, e_total)

Market clearing prices p: [1.   0.35]
Stochastic discount factor (SDF) in each state: [1.25 1.77]
Q: [0.74 0.26]
Price of the asset with payoffs A_1 is P_1 = 1.35
Price of the asset with payoffs A_2 is P_2 = 5.0
Aaron's optimal consumption: [381.1459316  320.49618836]
Baron's optimal consumption: [818.8540687  729.50381078]


array([ 3.04944024e-07, -8.62468823e-07])

In [ ]:
theta_B = 3.5
p_market_clearing = find_market_clearing_price(e_A, e_B, theta_A, theta_B, pi)
central_factor=1/p_market_clearing[0]
central_price=p_market_clearing*central_factor
print("Market clearing prices p:", np.round(central_price, 2))


# Compute the stochastic discount factor (SDF) for each state
m = central_price / pi  # SDF = Arrow prices / state probabilities
avg_m = np.dot(m , pi)  # Average SDF
print("Stochastic discount factor (SDF) in each state:", np.round(m, 2))
q= m * pi / avg_m
print("Q:", np.round(q, 2))

def compute_asset_price(A, m, pi):

    return np.sum(A * m * pi)

# Example usage
A_1 = np.array([1, 1])  
A_2 = np.array([5, 0])  
P_1 = compute_asset_price(A_1, m, pi)
P_2 = compute_asset_price(A_2, m, pi)

print("Price of the asset with payoffs A_1 is P_1 =", np.round(P_1, 2))
print("Price of the asset with payoffs A_2 is P_2 =", np.round(P_2, 2))
p = central_price  # Example Arrow prices (normalized to sum to 1)

# Compute optimal consumptions for each trader
x_A = compute_optimal_consumption(e_A, theta_A, p, pi)
x_B = compute_optimal_consumption(e_B, theta_B, p, pi)

print("Aaron's optimal consumption:", x_A)
print("Baron's optimal consumption:", x_B)

check_market_clearing(x_A, x_B, e_total)

Market clearing prices p: [1.   0.37]
Stochastic discount factor (SDF) in each state: [1.25 1.83]
Q: [0.73 0.27]
Price of the asset with payoffs A_1 is P_1 = 1.37
Price of the asset with payoffs A_2 is P_2 = 5.0
Aaron's optimal consumption: [384.61690646 318.25489307]
Baron's optimal consumption: [815.3830933  731.74510759]


array([-2.38782832e-07,  6.53968073e-07])

## (e)

In [35]:
theta_B = theta_A = 2.0  # Redefine Risk aversion coefficients
pi_A = np.array([0.8, 0.2])  # Probabilities of the states
pi_B = np.array([0.6, 0.4])  # Probabilities of the states

In [36]:
def find_market_clearing_price_different_expectation(e_A, e_B, theta_A, theta_B, pi_A, pi_B, tol=1e-6, max_iter=1000):
    p1 = 0.5  # Initial guess of p[0]
    p_bounds = np.array([0.0, 1.0])  # Bounds for p[0]
    err = 1  # Initialize error
    n_iter = max_iter  # Initialize iteration counter
    iteration = 1
    while (err > tol) and (n_iter > iteration):
        # print("Iteration :", iteration)
        iteration += 1
        # Define the price vector
        p = np.array([p1, 1 - p1])
        # Compute optimal consumptions for each trader
        x_A = compute_optimal_consumption(e_A, theta_A, p, pi_A)
        x_B = compute_optimal_consumption(e_B, theta_B, p, pi_B)
        # Check market clearing
        residuals = check_market_clearing(x_A, x_B, e_total)
        err = np.linalg.norm(residuals)

        # Check convergence
        if err > tol:
            if residuals[0] > 0:
                # print(f"Market clearing error is positive {residuals[0]}, increase p1")
                p1_new = (p_bounds[1] + p1) / 2
                p_bounds[0] = p1
                p1 = p1_new
                # print("New p1:", p1)
                # print("New bounds:", p_bounds)
            else:
                # print(f"Market clearing error is negative {residuals[0]}, decrease p1")
                p1_new = (p1 + p_bounds[0]) / 2
                p_bounds[1] = p1
                p1 = p1_new
                # print("New p1:", p1)
                # print("New bounds:", p_bounds)

    return np.array([p1, 1 - p1])

# Example usage
p_market_clearing = find_market_clearing_price_different_expectation(e_A, e_B, theta_A, theta_B, pi_A, pi_B)
central_factor=1/p_market_clearing[0]
central_price=p_market_clearing*central_factor
print("Market clearing prices p:", np.round(central_price, 2))


Market clearing prices p: [1.   0.63]


In [37]:

# Compute the stochastic discount factor (SDF) for each state
m = central_price / pi  # SDF = Arrow prices / state probabilities
avg_m = np.dot(m , pi)  # Average SDF
print("Stochastic discount factor (SDF) in each state:", np.round(m, 2))
q= m * pi / avg_m
print("Q:", np.round(q, 2))


Stochastic discount factor (SDF) in each state: [1.25 3.15]
Q: [0.61 0.39]


In [38]:
p = central_price  # Example Arrow prices (normalized to sum to 1)

# Compute optimal consumptions for each trader
x_A = compute_optimal_consumption(e_A, theta_A, p, pi_A)
x_B = compute_optimal_consumption(e_B, theta_B, p, pi_B)

print("Aaron's optimal consumption:", x_A)
print("Baron's optimal consumption:", x_B)

check_market_clearing(x_A, x_B, e_total)

Aaron's optimal consumption: [462.78535512 291.55736908]
Baron's optimal consumption: [737.21464524 758.44263036]


array([ 3.55865495e-07, -5.64981974e-07])

## (f)

In [39]:
theta_C = theta_B = theta_A = 2.0  # Redefine Risk aversion coefficients
pi_C = np.array([0.8, 0.2])  # Probabilities of the states
e_C = np.array([200, 400])  # Endowment for Charlie
e_total = e_A + e_B + e_C  # Total endowment

In [40]:
def check_market_clearing3(consumption_A, consumption_B, consumption_C, endowment_total):

    # Compute total consumption in each state
    total_consumption = consumption_A + consumption_B + consumption_C

    # Compute residuals
    residuals = total_consumption - endowment_total

    return residuals

In [41]:
def find_market_clearing_price_3a(e_A, e_B, e_C, theta_A, theta_B,theta_C, pi_A, pi_B, pi_C,tol=1e-6, max_iter=1000):
    p1 = 0.5  # Initial guess of p[0]
    p_bounds = np.array([0.0, 1.0])  # Bounds for p[0]
    err = 1  # Initialize error
    n_iter = max_iter  # Initialize iteration counter
    iteration = 1
    while (err > tol) and (n_iter > iteration):
        # print("Iteration :", iteration)
        iteration += 1
        # Define the price vector
        p = np.array([p1, 1 - p1])
        # Compute optimal consumptions for each trader
        x_A = compute_optimal_consumption(e_A, theta_A, p, pi_A)
        x_B = compute_optimal_consumption(e_B, theta_B, p, pi_B)
        x_C = compute_optimal_consumption(e_C, theta_C, p, pi_C)
        # Check market clearing
        residuals = check_market_clearing3(x_A, x_B, x_C, e_total)
        err = np.linalg.norm(residuals)

        # Check convergence
        if err > tol:
            if residuals[0] > 0:
                # print(f"Market clearing error is positive {residuals[0]}, increase p1")
                p1_new = (p_bounds[1] + p1) / 2
                p_bounds[0] = p1
                p1 = p1_new
                # print("New p1:", p1)
                # print("New bounds:", p_bounds)
            else:
                # print(f"Market clearing error is negative {residuals[0]}, decrease p1")
                p1_new = (p1 + p_bounds[0]) / 2
                p_bounds[1] = p1
                p1 = p1_new
                # print("New p1:", p1)
                # print("New bounds:", p_bounds)

    return np.array([p1, 1 - p1])

# Example usage
p_market_clearing = find_market_clearing_price_3a(e_A, e_B, e_C, theta_A, theta_B, theta_C, pi_A, pi_B, pi_C)
central_factor=1/p_market_clearing[0]
central_price=p_market_clearing*central_factor
print("Market clearing prices p:", np.round(central_price, 2))

Market clearing prices p: [1.   0.41]


In [42]:
# Compute the stochastic discount factor (SDF) for each state
m = central_price / pi  # SDF = Arrow prices / state probabilities
avg_m = np.dot(m , pi)  # Average SDF
print("Stochastic discount factor (SDF) in each state:", np.round(m, 2))
q= m * pi / avg_m
print("Q:", np.round(q, 2))

Stochastic discount factor (SDF) in each state: [1.25 2.06]
Q: [0.71 0.29]


In [43]:
p = central_price  # Example Arrow prices (normalized to sum to 1)

# Compute optimal consumptions for each trader
x_A = compute_optimal_consumption(e_A, theta_A, p, pi_A)
x_B = compute_optimal_consumption(e_B, theta_B, p, pi_B)
x_C = compute_optimal_consumption(e_C, theta_C, p, pi_C)

print("Aaron's optimal consumption:", x_A)
print("Baron's optimal consumption:", x_B)
print("Charlie's optimal consumption:", x_C)

check_market_clearing3(x_A, x_B, x_C, e_total)

Aaron's optimal consumption: [398.3798948  310.67585318]
Baron's optimal consumption: [725.6573779  924.11510371]
Charlie's optimal consumption: [275.96272746 215.20904272]


array([ 1.59184310e-07, -3.87240107e-07])